### ISSUE TITLE
swagger API versionning

### ISSUE THREAD

**Issue by FirasGL** [TimeIncOSS/swagger-bundle#17]
Hello, I am working on improving a swagger documentation with Symfony, and I want to know how I can handle the versioning of the API. Thank you

**Comment by Blackskyliner** [comment]
AFAIK Swagger keeps the way of versioning at your peril, which is good because there are multitude ways to version an API and thus the specification does not recommend/enforce a specific way. Use whats best for your use-case.

Just to name a few: Path Versioning (/path/to/api/v1/endpoint eg. /v1/status), Header Versioning (X-Api-Version: v1), Mediatype Versioning (eg. Accept/Content-Type: application/vnd.model.version+json eg. application/vnd.status.v1+json).

Mediatype and Path versioning can be easily integrated and used through the swagger-ui which parses swagger.json content, as you can define the different response mediatypes ("produces") and then select those as "Accept" wenn doing your call to the api. 

I guess mediatype versioning it's pretty inconvinient to use if you use the "Generate Client" stuff of swagger which consumes the swagger.json and generates you an client for an API which is pretty much ready-to-use (see editor.swagger.io for that feature). So if you need/want the ease of using the auto-client-generation stuff based on the generated swagger.json you should use (at least in my optinion) the path versioning. As you will then get a path-named function in the generated client. Like "nameOfTheApiV1Status($param1, $param2, ...)". 

As sidenote, the Mediatype and Path version are both pretty much compatible with a pristine REST definition (which, broken down, just states there must be a way for unique-access-identifier, access verbs and content-negotiation). 

The Header versioning stuff is kinda outdated nowadays and, as far as I am concerned a hassle to use and not really intuitive (as Pathes and Mediatypes can be advertised through HTTP, but custom headers can not, first through HATEOAS and the second through a 406 response with an Accept header for supported media types)
